# Generated by Django 4.1.3 on 2022-12-14 16:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=250)),
                ('imageURL', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=250)),
                ('imageURL', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('theory', models.TextField()),
                ('description', models.TextField()),
                ('imageURL', models.URLField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.categories')),
                ('first_question_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.questions')),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tests'),
        ),
    ]
