# Generated by Django 4.1.3 on 2022-12-23 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='first_question_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.questions'),
        ),
    ]
