# Generated by Django 4.1.3 on 2022-12-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='next_question_id',
            field=models.UUIDField(null=True),
        ),
    ]
